services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Bridge\PasswordServiceBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Bridge\PasswordServiceBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Service\PasswordVerificationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Service\PasswordVerificationService

  OxidEsales\EshopCommunity\Internal\Domain\Authentication\Policy\PasswordPolicyInterface:
    class: OxidEsales\EshopCommunity\Internal\Domain\Authentication\Policy\PasswordPolicy
