services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\EshopCommunity\Internal\Setup\Directory\Service\DirectoryServiceInterface:
        class: OxidEsales\EshopCommunity\Internal\Setup\Directory\Service\DirectoryService